/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "ADC.h"
#include "WaveDAC8_1.h"
#include "DAC_aliases.h"
#include "DAC.h"
#include "ADC_in_aliases.h"
#include "ADC_in.h"
#include "isr_adc.h"
#include "Pin_SW_aliases.h"
#include "Pin_SW.h"
#include "isr_button.h"
#include "uart_interrupt.h"
#include "LED_RED_aliases.h"
#include "LED_RED.h"
#include "LED_Green_aliases.h"
#include "LED_Green.h"
#include "LED_YELLOW_aliases.h"
#include "LED_YELLOW.h"
#include "UART_1_IntClock.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

